name: Prepare Rust Environment
description: 'Prepare Rust Build Environment'
runs:
  using: "composite"
  steps:
    - name: Configure runtime env
      shell: bash
      run: |
        echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
        echo "RUSTFLAGS=-C debuginfo=line-tables-only -C incremental=false" >> $GITHUB_ENV
