name: python-docs

on:
  push:
    branches: ["main"]
    paths:
      - "py-denormalized/**"
  pull_request:
    branches: ["main"]
    paths:
      - "py-denormalized/**"

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"
          enable-cache: true
          cache-dependency-glob: "py-denormalized/uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "py-denormalized/pyproject.toml"

      - name: Install the project
        working-directory: ./py-denormalized
        run: uv sync --no-dev --group docs --extra feast

      - name: Configure Virtual Environment
        working-directory: ./py-denormalized
        run: |
          source .venv/bin/activate
          pdoc -t pdocs/ python/denormalized/ -o pdocs/_build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: py-denormalized/pdocs/_build

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
