name: python-docs

on:
  push:
    branches: [ "main" ]
    paths:
      - 'py-denormalized/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'py-denormalized/**'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py-denormalized
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev
      - run: pdoc -t pdocs/ python/denormalized/ -o pdocs/_build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: pdocs/_build

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py-denormalized
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
